import express from 'express';
import mongoose from 'mongoose';
import cors from 'cors';
import dotenv from 'dotenv';
import { createServer } from 'http';
import { Server } from 'socket.io';
import Carton from './src/models/Carton.js';
import Settings from './src/models/Settings.js';

dotenv.config();

const app = express();
const httpServer = createServer(app);
const io = new Server(httpServer, {
    cors: {
        origin: "*", // Adjust in production
        methods: ["GET", "POST", "DELETE", "PUT"]
    }
});

app.use(cors());
app.use(express.json());

// --- Database Connection ---
mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/data-entry-db')
    .then(() => console.log('✅ MongoDB Connected'))
    .catch(err => console.error('❌ MongoDB Connection Error:', err));

// --- Socket.IO Logic ---
io.on('connection', (socket) => {
    console.log('🔌 Client Connected:', socket.id);

    // Join room? Not strictly needed for broadcast-all, but good practice
    socket.join('updates');

    socket.on('disconnect', () => {
        console.log('❌ Client Disconnected:', socket.id);
    });
});

// --- API Routes ---

// GET All Cartons
app.get('/api/cartons', async (req, res) => {
    try {
        const cartons = await Carton.find().sort({ timestamp: 1 });
        res.json(cartons);
    } catch (e) {
        res.status(500).json({ error: e.message });
    }
});

// POST (Add/Update) Carton
app.post('/api/cartons', async (req, res) => {
    try {
        const data = req.body;
        // Upsert based on _id if present, else create new
        // Ideally we use PUT for updates, but shared endpoint handling:
        let saved;
        if (data._id && mongoose.Types.ObjectId.isValid(data._id)) {
            saved = await Carton.findByIdAndUpdate(data._id, data, { new: true, upsert: true });
        } else {
            // Remove temp ID if it was generated by frontend (e.g. timestamp string)
            // Or if existing schema uses String IDs, we might keep it.
            // Let's assume we want Mongoose ObjectIds for real backend.
            // Frontend sends `_id: Date.now().toString()`. This is NOT a valid ObjectId.
            // We should strip it and let Mongo generate one, OR use a custom `cartonId`.
            // Let's strip the temp _id if it's not a valid ObjectId.
            const { _id, ...cleanData } = data;

            // If frontend _id is 24 chars, use it. If "1732..." (timestamp), drop it.
            if (_id && mongoose.Types.ObjectId.isValid(_id)) {
                // Update specific ID
                saved = await Carton.findByIdAndUpdate(_id, cleanData, { new: true, upsert: true });
            } else {
                // New
                saved = await Carton.create(cleanData);
            }
        }

        io.to('updates').emit('sync_cartons', { type: 'UPDATE', carton: saved });
        io.emit('sync_cartons', { type: 'REFRESH_ALL' }); // Simple fallback: tell everyone to re-fetch

        res.json(saved);
    } catch (e) {
        console.error(e);
        res.status(500).json({ error: e.message });
    }
});

// DELETE Carton
app.delete('/api/cartons/:id', async (req, res) => {
    try {
        await Carton.findByIdAndDelete(req.params.id);

        // Notify clients
        io.emit('sync_cartons', { type: 'DELETE', id: req.params.id });

        res.json({ success: true });
    } catch (e) {
        res.status(500).json({ error: e.message });
    }
});

// GET Settings
app.get('/api/settings', async (req, res) => {
    try {
        const settings = await Settings.findOne();
        res.json(settings || { activeSeason: 'WINTER 2025', extraSizes: [] });
    } catch (e) {
        res.status(500).json({ error: e.message });
    }
});

// POST Settings
app.post('/api/settings', async (req, res) => {
    try {
        const update = req.body;
        const settings = await Settings.findOneAndUpdate({}, update, { new: true, upsert: true });

        io.emit('sync_settings', settings);

        res.json(settings);
    } catch (e) {
        res.status(500).json({ error: e.message });
    }
});

// Upload Files (Simple Mock or Multer if needed later, ignoring for Sync task unless requested)
app.post('/api/upload', (req, res) => {
    res.json({ message: "File upload endpoint placeholder" });
});

const PORT = 5000;
httpServer.listen(PORT, () => {
    console.log(`🚀 Server running on http://localhost:${PORT}`);
    console.log(`📡 Socket.IO enabled`);
});
