export const BUYER_OPTIONS = ['DUNS', 'MORE THAN A FLINGS'];

export const SIZES = [
    '45', '47', '68', '74', '80', '86', '92', '98',
    '104', '110', '116', '122', '128', '134', '140',
    'S', 'M', 'L', 'XL', 'XXL', 'XXXL', 'XXXXL'
];

export const PRINT_OPTIONS = [
    "Beach Pig",
    "Beach Pig. River Blue Taping",
    "Camelia Rose Dark Pink",
    "Chiffon Lilac",
    "Clover – Dandelion Yellow",
    "Clover – Dandelion Yellow. Blazing Orange Taping",
    "Clover – Sulphur Spring Green. River Blue Taping",
    "Clover – Vibrant Orange",
    "Clover – Vibrant Orange. Marina Blue Taping",
    "Fruits – Beach Glass",
    "Fruits – Beach Glass. French Blue Taping",
    "Fruits – Blushing Bride",
    "Fruits – Blushing Bride. Camelia Rose Pink Taping",
    "Happy Flower. Lilac Chiffon",
    "Happy Flower. Lilac Chiffon Taping",
    "Happy Flower. Patina Green Taping",
    "Jellyfish. Marina Blue Taping",
    "Jumbled Radish – Blue",
    "Jumbled Radish – Blue. River Blue Taping",
    "Jumbled Radish- Blue . River Blue Taping",
    "Jumbled Radish- Blue. River Blue Taping",
    "Jumbled Radish- Pink, Lilac Chiffon Taping",
    "Marina Blue",
    "Multi Radish – Blue",
    "Multi Radish – Blue. Marina Blue Taping",
    "Multi Radish – Pink",
    "Multi Radish – Pink. Camelia Rose Pink Taping",
    "Radish – Lilac Chiffon. Lilac Chiffon Taping",
    "Radish – Marina Blue",
    "Radish – Marina Blue. Marina Blue Taping",
    "Radish – Patina Green. Patina Green Taping",
    "Radish – Sunshine Pale Yellow. Dandelion Yellow Taping",
    "Radish – Lilac Chiffon"
];

export const STYLE_OPTIONS = [
    "Baggy Pants",
    "Bedding",
    "Bonnet",
    "Dungaree",
    "Hood Suit",
    "Kimono Body",
    "Knot Hat",
    "Long Sleeve Lap Neck Body",
    "Long Sleeve Lap Neck Suit",
    "LONG SLEEVE Skater Dress",
    "Long Sleeve Top",
    "More Than a Fling - Baggy Pants",
    "More Than a Fling - Lap Neck Body",
    "More Than a Fling - Long Sleeve Top",
    "More Than a Fling - Short Pants",
    "More Than a Fling - Short Sleeve Top",
    "More Than a Fling - Leggings",
    "Play Suit",
    "S/S Skater Dress",
    "Short Pants",
    "Short Sleeve Skater Dress",
    "Short Sleeve Top",
    "Sleeveless Gather Dress",
    "Summer Suit",
    "Sun Hat",
    "Terry Pants",
    "Terry Short Pants",
    "Zip Suit"
];
